title: <p align="center"> Sopi S </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="resume.pdf">Resume</a> |
  <a href="linkedin.com/in/sopi-siti-sopiah-356750222/">LinkedIn</a> |
  <a href="https://github.com/sopists">GitHub</a>
  </p>
  
  <p align="justify">
  I am an university student of Majoring Development Economics at Faculty of Economic, University of Nahdlatul Ulama Al-Ghazali Cilacap.
  <br><br>
  I am currently a Data Analytics Student at Program Zenius Study Independent.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
